spring-application.name=api-gateway
server.port=8080

#Since it's a server,we don't want it to register and
#also don't want to fetch the instances details
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=true

# Allow self-discovery (since gateway is also a client)
eureka.client.service-url.defaultZone=http://localhost:8080/eureka


# ===============================
# ACTUATOR BASE CONFIG
# ===============================

management.endpoints.web.base-path=/actuator

# Expose only required endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus,loggers,threaddump

# ===============================
# HEALTH CONFIGURATION
# ===============================

# Show details only to authorized users
management.endpoint.health.show-details=when_authorized

# Enable liveness & readiness probes (Kubernetes-ready)
management.endpoint.health.probes.enabled=true

# Enable specific health indicators
management.health.db.enabled=true
management.health.diskspace.enabled=true

# ===============================
# ACTUATOR PORT (OPTIONAL)
# ===============================

# Run actuator on separate port (recommended in production)
#management.server.port=8081

# ===============================
# APPLICATION INFO
# ===============================

info.app.name=api-gateway
info.app.version=1.0.0
info.app.description=API GATEWAY

# ===============================
# METRICS & PROMETHEUS
# ===============================

management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true

# ===============================
# LOGGING (OPTIONAL)
# ===============================

# Default logging level
logging.level.root=INFO

# Example: increase logging for your package
logging.level.com.platform=INFO


